name: Deploy

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remote connecting to server using SSH, then build and deploy the dockerize project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/github/linxtstudio
            sudo git pull origin main
            sudo docker build -t linxtstudio/landing-page .
            sudo docker stop linxtstudio-landing-page
            sudo docker rm linxtstudio-landing-page
            sudo docker run -d -p 20000:3000 --name linxtstudio-landing-page linxtstudio/landing-page
            sudo docker image prune -f
            curl --location --request POST ${{ secrets.DISCORD_WEBHOOK }} \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'Cookie: __dcfduid=d0a4610ec17011ec9f4dd62042431c85; __sdcfduid=d0a4610ec17011ec9f4dd62042431c85ed313225b75c32b3e67e485b68e0df95002206f783f87c3b5ab8c89ede4eb5a5' \
            --data-raw '{"embeds": [{"title": "Landing Page Pipeline","description": "Berhasil Deploy Project Linxt Studio Landing Page","url": "https://github.com/linxtstudio/linxtstudio","color": 2895667,"provider": {"name": "Linxt Studio","url": "https://github.com/linxtstudio/linxtstudio"},"fields": [{"name": "Source Branch","value": "${{ github.head_ref }}","inline": true},{"name": "Target Branch","value": "${{ github.base_ref }}","inline": true},{"name": "Author","value": "${{ github.event.commits[0].author.name }}","inline": false},{"name": "Commit Message","value": "${{ github.event.commits[0].message }}","inline": false}]}]}'
