name: Deploy

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Remote connecting to server using SSH, then build and deploy the dockerize project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd ~/github/linxtstudio
            sudo git pull origin main
            sudo docker build -t linxtstudio/landing-page .
            sudo docker stop linxtstudio-landing-page
            sudo docker rm linxtstudio-landing-page
            sudo docker run -d -p 20000:3000 --name linxtstudio-landing-page linxtstudio/landing-page
            sudo docker image prune -f
            curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST -data ${{ toJson({"embeds":[{"title":"Landing Page Pipeline","description":"Berhasil Deploy Project Linxt Studio Landing Page","url":"https://github.com/linxtstudio/linxtstudio","color":2895667,"provider":{"name":"Linxt Studio","url":"https://github.com/linxtstudio/linxtstudio"},"fields":[{"name":"Source Branch","value":"${{ github.head_ref }}","inline":true},{"name":"Target Branch","value":"${{ github.base_ref }}","inline":true},{"name":"Author","value":"${{ github.event.commits[0]['author']['name'] }}","inline":false},{"name":"Commit Message","value":"${{ github.event.commits[0]['message'] }}","inline":false}]}]}) }} ${{ secrets.DISCORD_WEBHOOK }}
            
      - name: Notifying discord webhook that deployment has been done successfully
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
        

